
FROM us-docker.pkg.dev/cookies-eng/public/base/codespaces:v1j@sha256:11ad9980e5d9c3292f8e300f127079fd829a18b2fadedb7e979d890a7003741a

ENV SHELL=zsh \
    HOME=/home/dev \
    DEVCONTAINER=yes

USER dev
WORKDIR /home/dev
