
FROM us-docker.pkg.dev/cookies-eng/public/base/codespaces:v1j@sha256:dfdace14f3e73026ccda637013eca1aad19fa886ee101ba475ca38f62ef3356a

ENV SHELL=zsh \
    HOME=/home/dev \
    DEVCONTAINER=yes

USER dev
WORKDIR /home/dev
